### ISSUE TITLE
Rep issue

### ISSUE THREAD

**Issue by DanielCarter1615** [ian-travers/nfsu-server#2]
@ian-travers Continuing here with our discussion here.

Today I tested the new nfsu-server, and here are my conclusions regarding rep:
- the issue is fixed, that in rooms the wrong rep would be shown in ranked mode.
- sometimes there are rep points shown in the unranked room, sometimes not. Maybe this can be handled like in ranked room, to just show always the rep points?
- there is still this issue: when someone disconnects, because he didn't move, that he gets a win. And the other player gets credited the loss.
- If someone Alt-F4 the game, then he also doesn't get a loss (but at least the other player gets the win).

**Comment by ian-travers** [comment]
I guess showing REP in an unranked room is not an issue. Actually, it's not a secret. The player can see it in "View Player Details".

About a disconnection. Determination that the player has finished occurs when processing the `rept` replica.  ([see](https://github.com/ian-travers/nfsu-server/blob/main/NFSUServer2/nfsuserver.cpp#L1124))
Unfortunately I could not figure out when the disconnect is counted. Therefore, so that the wins are definitely not counted as losses  and it happens like this. Tell you more. The `rank` replica is sent to the server when a player quit the lobby after a race. So if you exit the game before quiting to the lobby, the statistics will not change.

it seems to me that for further improvement it is necessary to introduce sessions. Now we have sessions. But this is a small semantic caveat. In its current form, the session is a race. It would be nice to implement real sessions, and consider the race already inside the session of each player.

This will allow processing the `skey` replica and consider `skey` param in some other replicas.This may lead to the head-to-head issue.

**Comment by DanielCarter1615** [comment]
understood, thanks for the explanation.
